apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/JM-TEFFU/Petclinic
    targetRevision: HEAD  # or the specific branch/tag you want to use
    path: .  # Use '.' if it's in the root, or specify a different path if needed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
